[package]
name = "turboshake"
version = "0.1.4"
edition = "2021"
authors = ["Anjan Roy <hello@itzmeanjan.in>"]
description = "A family of extendable output functions based on keccak-p[1600, 12] permutation"
documentation = "https://github.com/itzmeanjan/turboshake"
readme = "README.md"
repository = "https://github.com/itzmeanjan/turboshake.git"
license = "MIT"
keywords = ["cryptography", "keccak", "xof", "hashing", "turboshake"]
categories = ["cryptography"]

[features]
dev = []
simdx2 = []
simdx4 = []

[dependencies]
crunchy = "0.2.2"

[dev-dependencies]
rand = "0.8.5"
hex = "0.4.3"
criterion = "0.4.0"
test-case = "3.0.0"

[lib]
bench = false

[[bench]]
name = "keccak"
harness = false
required-features = ["dev"]

[[bench]]
name = "turboshake"
harness = false

[[example]]
name = "keccak"
required-features = ["dev"]

[[example]]
name = "simd_keccak"
required-features = ["dev", "simdx4"]
