name: TurboSHAKE

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: RUSTFLAGS="-C opt-level=3 -C target-cpu=native" cargo test --lib --features simdx2,simdx4
    - name: Run examples
      run: cargo run --example turboshake128 && cargo run --example turboshake256
